-- vim.api.nvim_create_autocmd("BufEnter", {
-- 	group = vim.api.nvim_create_augroup("theme_swithcer", {}),
-- 	callback = function()
-- 		if vim.bo.filetype == "lua" then
-- 			vim.cmd.colorscheme('tokyonight-night')
-- 		elseif vim.bo.filetype == "typescript" then
-- 			vim.cmd.colorscheme('tokyonight')
-- 		elseif vim.bo.filetype == "svelte" then
-- 			vim.cmd.colorscheme('monokai-pro')
-- 		elseif vim.bo.filetype == "rust" then
-- 			vim.cmd.colorscheme('gruvbox-baby')
-- 		else
-- 			vim.cmd.colorscheme('rose-pine-moon')
-- 		end
-- 	end,
-- })
